name: "Test"
on:
  push:
    branches:
      - master
    paths:
      - "git-app/*/**"
    tags-ignore:
      - v*.*.*
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "git-app/*/**"
jobs:
  git-app-test:
    name: git-app-test
    timeout-minutes: 10
    runs-on: ubuntu-latest-4core
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for SonarCloud analysis
      - name: Install dependencies
        run: |
          npm ci
